services:
  project01:
    image: project1image:v1
    build:
      context: .
      dockerfile: ProjectMicroservice/ProjectMicroservice/Dockerfile
  project02:
    image: project2image:v1
    build:
      context: .
      dockerfile: CodeFirstApi/CodeFirstApi/Dockerfile
  project03:
    image: project3image:v4
    build:
      context: .
      dockerfile: CodeFirstMicroservice/CodeFirstMicroservice/Dockerfile
  apigateway:
    image: apigatewayimg:v4
    build:
      context: .
      dockerfile: APIGateway/APIGateway/Dockerfile
